# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Promptbucket < Formula
  desc "A CLI tool for managing prompt buckets"
  homepage "https://github.com/promptbucket/cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/promptbucket/cli/releases/download/v0.1.0/promptbucket_Darwin_x86_64.tar.gz"
      sha256 "a20c70e9a3ab82295bb1e6490955a13f7350e74113199c028ec01984906f9f12"

      def install
        bin.install "promptbucket"
      end
    end
    on_arm do
      url "https://github.com/promptbucket/cli/releases/download/v0.1.0/promptbucket_Darwin_arm64.tar.gz"
      sha256 "1b35374ce484c0c6a72eb6d30ca920acdbf10342c72c1466c9f3f49638b1b5a4"

      def install
        bin.install "promptbucket"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/promptbucket/cli/releases/download/v0.1.0/promptbucket_Linux_x86_64.tar.gz"
        sha256 "da485f49a89288fdb7b9433168db7b62961fcc7780ef448d9b54ee6d04bb384d"

        def install
          bin.install "promptbucket"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/promptbucket/cli/releases/download/v0.1.0/promptbucket_Linux_arm64.tar.gz"
        sha256 "7f6a8a1a696185d1330d207c6a78896f6de08ed12d6ac15b80f2665eb530ce11"

        def install
          bin.install "promptbucket"
        end
      end
    end
  end

  test do
    system "#{bin}/promptbucket", "version"
  end
end
